"""
CommSpec Prototype — Requirements & Test Creation Tool for SAP Commissions
Throwaway single-file prototype demonstrating the core loop:

  1. Upload source documents (PDF, TXT, DOCX, pasted text)
  2. AI extracts requirement candidates (SAP Commissions domain-aware)
  3. AI composes a structured, approval-ready requirement
  4. Human reviews and approves or rejects
  5. On approval — AI generates test cases (hard gate)
  6. Export test cases as JSON

Run: venv\Scripts\python Commission.py  →  http://localhost:5002

NOTE: This is a prototype. All state is in-memory per browser session.
      For production architecture, see CommSpec_Blueprint.md.
"""

import os
import io
import re
import json
import uuid
from datetime import datetime

from flask import Flask, render_template_string, request, session, redirect, url_for, Response
from anthropic import Anthropic
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__)
app.secret_key = os.environ.get("SECRET_KEY", "commspec-proto-dev-key")
client = Anthropic()

COMPONENTS = ["Workflow", "BTP_EDL", "ICM_Engine", "Embedded_Analytics", "Integration",
              "Participants", "Credit_Incentive", "Batch_Scheduling", "Security"]

COMPONENT_CODES = {
    "Workflow": "WF", "BTP_EDL": "EDL", "ICM_Engine": "ICM",
    "Embedded_Analytics": "ANA", "Integration": "INT",
    "Participants": "PAR", "Credit_Incentive": "CR",
    "Batch_Scheduling": "BAT", "Security": "SEC",
}


# ── In-memory store ────────────────────────────────────────────────────────────
_store = {}

def get_state(sid):
    if sid not in _store:
        _store[sid] = {
            "sources": [],           # list of {id, name, type, content, uploaded_at}
            "component": "Workflow",
            "candidates": [],        # extracted by AI
            "gaps": [],
            "open_questions": [],
            "conflicts": [],
            "requirement": None,     # composed by AI, then human-approved
            "test_cases": [],        # generated by AI after approval
            "stage": "intake",       # intake | review | approval | tests
            "processing": False,
            "error": None,
        }
    return _store[sid]


# ── File parsing ───────────────────────────────────────────────────────────────
def parse_upload(f):
    ext = f.filename.rsplit(".", 1)[-1].lower() if "." in f.filename else "txt"
    data = f.read()
    if ext == "pdf":
        try:
            import pdfplumber
            with pdfplumber.open(io.BytesIO(data)) as pdf:
                pages = [pg.extract_text() or "" for pg in pdf.pages]
            return "\n\n".join(p for p in pages if p.strip())
        except Exception as e:
            return f"[PDF parse error: {e}]"
    elif ext == "docx":
        try:
            import docx as _docx
            doc = _docx.Document(io.BytesIO(data))
            return "\n".join(p.text for p in doc.paragraphs if p.text.strip())
        except Exception as e:
            return f"[DOCX parse error: {e}]"
    else:
        return data.decode("utf-8", errors="replace")


# ── AI layer ───────────────────────────────────────────────────────────────────
def call_claude(prompt: str, max_tokens: int = 4096) -> str:
    resp = client.messages.create(
        model="claude-opus-4-6",
        max_tokens=max_tokens,
        messages=[{"role": "user", "content": prompt}],
    )
    return resp.content[0].text.strip()


def parse_json_response(text: str):
    text = re.sub(r"^```(?:json)?\n?", "", text.strip())
    text = re.sub(r"\n?```$", "", text)
    return json.loads(text)


def ai_extract(sources_text: str, component: str) -> dict:
    code = COMPONENT_CODES.get(component, "XX")
    prompt = f"""You are a senior SAP Commissions business analyst and functional architect.

Analyze the following source material and extract requirement candidates for the {component} component of SAP Commissions.

SOURCE MATERIAL:
---
{sources_text[:12000]}
---

Extract every requirement-relevant statement. For each candidate return:
- statement: precise, non-vague requirement text
- candidate_type: one of RULE | ACTOR | TRIGGER | VALIDATION | EXCEPTION | DATA_FIELD | INTEGRATION | REPORTING | SECURITY | NON_FUNCTIONAL
- confidence: 0.0–1.0 (how clearly stated in source vs inferred)
- source_quote: verbatim excerpt (max 120 chars) supporting this candidate
- is_inferred: true if you derived it, false if explicitly stated
- component: {component}

Also identify:
- gaps: missing information, undefined actors, untestable acceptance conditions
- open_questions: questions the material raises but does not answer
- conflicts: any contradictory statements in the material

SAP Commissions domain context: be specific to Workflow state machines, BTP/EDL pipeline patterns, ICM crediting/calculation logic, Embedded Analytics KPIs, integration handoffs, participant/position structures, period-close behavior, and security roles as applicable.

Return ONLY valid JSON — no preamble:
{{
  "candidates": [
    {{"statement": "", "candidate_type": "", "confidence": 0.0, "source_quote": "", "is_inferred": false, "component": ""}}
  ],
  "gaps": [{{"description": "", "severity": "HIGH|MEDIUM|LOW"}}],
  "open_questions": [{{"question": "", "why_it_matters": ""}}],
  "conflicts": [{{"statement_a": "", "statement_b": "", "description": ""}}]
}}

If source material is too thin to extract meaningful requirements, state this in gaps. Do NOT hallucinate SAP Commissions-specific logic not present in the source."""

    return parse_json_response(call_claude(prompt))


def ai_compose(candidates: list, gaps: list, open_questions: list, component: str) -> dict:
    code = COMPONENT_CODES.get(component, "XX")
    prompt = f"""You are a senior SAP Commissions functional consultant writing an enterprise-grade requirement.

COMPONENT: {component}
REQUIREMENT CANDIDATES:
{json.dumps(candidates, indent=2)}

IDENTIFIED GAPS:
{json.dumps(gaps, indent=2)}

OPEN QUESTIONS:
{json.dumps(open_questions, indent=2)}

Produce one complete, structured SAP Commissions requirement. Every field must be populated.
If a field cannot be completed from available evidence, write "INSUFFICIENT INFORMATION: [reason]" — do not guess or invent.

Requirements for business rules: precise enough that a developer can implement without follow-up questions.
Requirements for acceptance criteria: every criterion must be individually testable. Set testable=false if not.
quality_score: 0.0–1.0 reflecting completeness and testability of this requirement.

Return ONLY valid JSON:
{{
  "req_id": "REQ-{code}-001",
  "title": "",
  "business_objective": "",
  "in_scope": [],
  "out_of_scope": [],
  "background": "",
  "actors": [{{"role": "", "description": "", "type": "human|system"}}],
  "preconditions": [],
  "trigger": "",
  "main_flow": [{{"step": 1, "actor": "", "action": "", "system_response": ""}}],
  "exception_flows": [{{"condition": "", "handling": "", "owner": ""}}],
  "business_rules": [],
  "data_requirements": [{{"field": "", "source_system": "", "validation_rule": ""}}],
  "integration_touchpoints": [],
  "assumptions": [{{"text": "", "is_inferred": true}}],
  "open_questions": [{{"question": "", "blocking": true}}],
  "acceptance_criteria": [{{"id": "AC-001", "text": "", "testable": true}}],
  "risks": [{{"description": "", "severity": "HIGH|MEDIUM|LOW", "mitigation": ""}}],
  "quality_score": 0.0
}}"""

    return parse_json_response(call_claude(prompt, max_tokens=6000))


def ai_generate_tests(requirement: dict, component: str) -> list:
    code = COMPONENT_CODES.get(component, "XX")
    prompt = f"""You are a senior QA lead and SAP Commissions domain expert.

Generate comprehensive, enterprise-grade test cases for this approved SAP Commissions requirement.

REQUIREMENT:
{json.dumps(requirement, indent=2)}

Generate test cases across ALL of these types:
- POSITIVE (2 minimum): happy path, all preconditions met
- NEGATIVE (2 minimum): invalid input, wrong role, wrong state, missing data
- BOUNDARY (1 minimum): threshold values, date edges, numeric limits
- EXCEPTION (1 minimum): system failure, timeout, integration non-response
- SECURITY (1 minimum): correct role has access, incorrect role is denied
- WORKFLOW (1 minimum): state transition, escalation, SLA breach

For each test case:
{{
  "case_id": "TC-{code}-001-01",
  "scenario_group": "scenario title grouping these related tests",
  "title": "",
  "test_type": "POSITIVE|NEGATIVE|BOUNDARY|EXCEPTION|SECURITY|WORKFLOW",
  "objective": "",
  "preconditions": [],
  "test_data_requirements": "",
  "steps": [{{"step": 1, "action": "", "expected_result": ""}}],
  "overall_expected_result": "",
  "acceptance_criterion_id": "AC-001",
  "priority": "CRITICAL|HIGH|MEDIUM|LOW",
  "component": "{component}",
  "sap_commissions_notes": ""
}}

CRITICAL RULES:
- Reference actual SAP Commissions field names, role names, screen names, and status values from the requirement
- Every step must be executable by a real QA team without guessing
- Link every test case to a specific acceptance criterion from the requirement
- Do NOT generate generic steps like "verify system works correctly"

Return ONLY valid JSON: {{"test_cases": [...]}}"""

    result = parse_json_response(call_claude(prompt, max_tokens=8000))
    return result.get("test_cases", [])


# ── HTML Base Layout ───────────────────────────────────────────────────────────
def base(content: str, stage: str = "intake", error: str = None) -> str:
    stages = [
        ("intake",   "1", "Source Upload"),
        ("review",   "2", "Review & Compose"),
        ("approval", "3", "Approval"),
        ("tests",    "4", "Test Generation"),
    ]
    stage_order = [s[0] for s in stages]
    current_idx = stage_order.index(stage) if stage in stage_order else 0

    steps_html = ""
    for i, (s_key, s_num, s_label) in enumerate(stages):
        if i < current_idx:
            cls = "flex items-center gap-2 text-emerald-600 font-medium text-sm"
            dot = "w-7 h-7 rounded-full bg-emerald-100 border-2 border-emerald-400 flex items-center justify-center text-emerald-600 font-bold text-xs"
            icon = "✓"
        elif i == current_idx:
            cls = "flex items-center gap-2 text-indigo-700 font-semibold text-sm"
            dot = "w-7 h-7 rounded-full bg-indigo-600 flex items-center justify-center text-white font-bold text-xs"
            icon = s_num
        else:
            cls = "flex items-center gap-2 text-slate-400 text-sm"
            dot = "w-7 h-7 rounded-full bg-slate-100 border-2 border-slate-200 flex items-center justify-center text-slate-400 font-bold text-xs"
            icon = s_num

        connector = '<div class="w-8 h-0.5 bg-slate-200 mx-1"></div>' if i < len(stages) - 1 else ""
        steps_html += f'<div class="{cls}"><div class="{dot}">{icon}</div><span class="hidden sm:inline">{s_label}</span></div>{connector}'

    error_banner = ""
    if error:
        error_banner = f'<div class="bg-red-50 border border-red-200 text-red-700 text-sm px-4 py-3 rounded-lg mb-4">⚠ {error}</div>'

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>CommSpec — SAP Commissions Requirements Tool</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet"/>
  <script>tailwind.config = {{ theme: {{ extend: {{ fontFamily: {{ sans: ['Inter','sans-serif'] }} }} }} }}</script>
  <style>
    body {{ -webkit-font-smoothing: antialiased; }}
    .card {{ background:#fff; border:1px solid #e2e8f0; border-radius:0.75rem; padding:1.25rem; }}
    .badge-rule     {{ background:#dbeafe; color:#1d4ed8; }}
    .badge-actor    {{ background:#f3e8ff; color:#7e22ce; }}
    .badge-trigger  {{ background:#fef9c3; color:#854d0e; }}
    .badge-exception{{ background:#fee2e2; color:#991b1b; }}
    .badge-validation{{ background:#dcfce7; color:#15803d; }}
    .badge-other    {{ background:#f1f5f9; color:#475569; }}
    .badge-positive {{ background:#dcfce7; color:#15803d; }}
    .badge-negative {{ background:#fee2e2; color:#991b1b; }}
    .badge-boundary {{ background:#fef9c3; color:#854d0e; }}
    .badge-security {{ background:#ede9fe; color:#6d28d9; }}
    .badge-workflow {{ background:#dbeafe; color:#1d4ed8; }}
    .badge-exception-test {{ background:#fce7f3; color:#9d174d; }}
    .badge-integration {{ background:#e0f2fe; color:#075985; }}
    .badge-data {{ background:#f0fdf4; color:#166534; }}
    .conf-high   {{ color:#15803d; font-weight:600; }}
    .conf-med    {{ color:#854d0e; font-weight:600; }}
    .conf-low    {{ color:#991b1b; font-weight:600; }}
    ::-webkit-scrollbar {{ width:5px; }}
    ::-webkit-scrollbar-thumb {{ background:#cbd5e1; border-radius:3px; }}
  </style>
</head>
<body class="bg-slate-50 font-sans min-h-screen">

<header class="bg-white border-b border-slate-200 px-6 py-3 flex items-center justify-between">
  <div class="flex items-center gap-2.5">
    <div class="w-8 h-8 bg-indigo-600 rounded-lg flex items-center justify-center text-white font-bold text-sm">CS</div>
    <div>
      <span class="font-semibold text-slate-800">CommSpec</span>
      <span class="text-slate-400 text-sm ml-1.5">SAP Commissions — Requirements &amp; Test Tool</span>
    </div>
  </div>
  <a href="/" class="text-xs text-slate-400 hover:text-red-500 transition-colors">↺ Reset</a>
</header>

<div class="max-w-5xl mx-auto px-4 py-6">
  <!-- Progress -->
  <div class="flex items-center justify-center mb-8 py-3 bg-white border border-slate-200 rounded-xl px-6">
    {steps_html}
  </div>

  {error_banner}
  {content}
</div>

<script>
function showSpinner(btn, msg) {{
  btn.disabled = true;
  btn.innerHTML = '<svg class="animate-spin w-4 h-4 inline mr-2" fill="none" viewBox="0 0 24 24"><circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle><path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8z"></path></svg>' + msg;
}}
</script>
</body>
</html>"""


# ── Page builders ──────────────────────────────────────────────────────────────

def page_intake(state: dict) -> str:
    sources_html = ""
    if state["sources"]:
        rows = ""
        for s in state["sources"]:
            rows += f"""<tr class="border-b border-slate-100 last:border-0">
              <td class="py-2 pr-4 text-sm font-medium text-slate-700">{s['name']}</td>
              <td class="py-2 pr-4"><span class="px-2 py-0.5 bg-slate-100 text-slate-600 text-xs rounded-full">{s['type']}</span></td>
              <td class="py-2 text-xs text-slate-400">{s['uploaded_at']}</td>
            </tr>"""
        sources_html = f"""
        <div class="card mt-4">
          <div class="flex items-center justify-between mb-3">
            <h3 class="text-sm font-semibold text-slate-700">Uploaded Sources ({len(state['sources'])})</h3>
          </div>
          <table class="w-full"><tbody>{rows}</tbody></table>
        </div>"""

    comp_opts = "".join(
        f'<option value="{c}" {"selected" if c == state["component"] else ""}>{c.replace("_"," ")}</option>'
        for c in COMPONENTS
    )

    extract_btn = ""
    if state["sources"]:
        extract_btn = """
        <form method="POST" action="/extract" class="mt-4">
          <button type="submit" onclick="showSpinner(this,'Extracting & composing requirement...')"
            class="w-full py-2.5 bg-indigo-600 hover:bg-indigo-700 text-white font-medium rounded-lg text-sm transition-colors">
            ⚡ Extract &amp; Compose Requirement
          </button>
          <p class="text-xs text-slate-400 mt-2 text-center">This sends your source material to Claude for requirement extraction. Takes 30–60 seconds.</p>
        </form>"""

    return f"""
    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">

      <!-- Upload file -->
      <div class="card">
        <h2 class="text-sm font-semibold text-slate-700 uppercase tracking-wide mb-3">Upload Source Document</h2>
        <form method="POST" action="/upload-file" enctype="multipart/form-data" class="space-y-3">
          <div>
            <label class="text-xs font-medium text-slate-600 block mb-1">SAP Commissions Component</label>
            <select name="component" class="w-full px-3 py-2 text-sm border border-slate-200 rounded-lg focus:outline-none focus:border-indigo-400">{comp_opts}</select>
          </div>
          <div>
            <label class="text-xs font-medium text-slate-600 block mb-1">File <span class="font-normal text-slate-400">(PDF, DOCX, TXT)</span></label>
            <input type="file" name="file" accept=".pdf,.docx,.txt,.csv"
              class="w-full text-sm text-slate-500 file:mr-3 file:py-1.5 file:px-3 file:rounded-lg file:border-0 file:bg-indigo-50 file:text-indigo-700 file:font-medium hover:file:bg-indigo-100"/>
          </div>
          <button type="submit" class="w-full py-2 bg-slate-800 hover:bg-slate-900 text-white text-sm font-medium rounded-lg transition-colors">
            Upload Document
          </button>
        </form>
      </div>

      <!-- Paste text -->
      <div class="card">
        <h2 class="text-sm font-semibold text-slate-700 uppercase tracking-wide mb-3">Paste Source Text</h2>
        <form method="POST" action="/upload-text" class="space-y-3">
          <div>
            <label class="text-xs font-medium text-slate-600 block mb-1">SAP Commissions Component</label>
            <select name="component" class="w-full px-3 py-2 text-sm border border-slate-200 rounded-lg focus:outline-none focus:border-indigo-400">{comp_opts}</select>
          </div>
          <div>
            <label class="text-xs font-medium text-slate-600 block mb-1">Source name</label>
            <input type="text" name="name" placeholder="e.g. Meeting Notes 2024-03-01"
              class="w-full px-3 py-2 text-sm border border-slate-200 rounded-lg focus:outline-none focus:border-indigo-400"/>
          </div>
          <div>
            <label class="text-xs font-medium text-slate-600 block mb-1">Content</label>
            <textarea name="content" rows="5" placeholder="Paste meeting notes, emails, BRD extracts, chat transcripts..."
              class="w-full px-3 py-2 text-sm border border-slate-200 rounded-lg focus:outline-none focus:border-indigo-400 resize-none"></textarea>
          </div>
          <button type="submit" class="w-full py-2 bg-slate-800 hover:bg-slate-900 text-white text-sm font-medium rounded-lg transition-colors">
            Add Source
          </button>
        </form>
      </div>
    </div>

    {sources_html}
    {extract_btn}

    <div class="mt-6 p-4 bg-amber-50 border border-amber-200 rounded-lg text-xs text-amber-800">
      <strong>Prototype note:</strong> This is a single-file demo. Upload one or more source documents (BRDs, meeting notes, emails, design docs), select the SAP Commissions component, then click Extract. All state is in-memory for this browser session only.
    </div>"""


def page_review(state: dict) -> str:
    req = state.get("requirement", {})
    candidates = state.get("candidates", [])
    gaps = state.get("gaps", [])
    open_qs = state.get("open_questions", [])
    conflicts = state.get("conflicts", [])

    # Quality score indicator
    qs = req.get("quality_score", 0)
    qs_color = "emerald" if qs >= 0.7 else "amber" if qs >= 0.4 else "red"
    qs_pct = int(qs * 100)

    # Candidates summary
    cand_html = ""
    for c in candidates[:15]:
        ct = c.get("candidate_type", "other").lower()
        badge_cls = f"badge-{ct}" if ct in ["rule","actor","trigger","exception","validation"] else "badge-other"
        conf = c.get("confidence", 0)
        conf_cls = "conf-high" if conf >= 0.7 else "conf-med" if conf >= 0.4 else "conf-low"
        inferred = '<span class="text-xs text-amber-600 ml-1">⚑ inferred</span>' if c.get("is_inferred") else ""
        cand_html += f"""<div class="border-b border-slate-100 last:border-0 py-2">
          <div class="flex items-start gap-2">
            <span class="px-1.5 py-0.5 rounded text-xs font-semibold {badge_cls} whitespace-nowrap flex-shrink-0">{c.get('candidate_type','')}</span>
            <div class="flex-1">
              <p class="text-sm text-slate-700">{c.get('statement','')}{inferred}</p>
              <p class="text-xs text-slate-400 mt-0.5 italic">"{c.get('source_quote','')}"</p>
            </div>
            <span class="{conf_cls} text-xs flex-shrink-0">{int(conf*100)}%</span>
          </div>
        </div>"""
    if len(candidates) > 15:
        cand_html += f'<p class="text-xs text-slate-400 pt-2">... and {len(candidates)-15} more candidates</p>'

    # Gaps and open questions
    issues_html = ""
    if gaps:
        for g in gaps:
            sev = g.get("severity","MEDIUM")
            sev_cls = "text-red-600" if sev == "HIGH" else "text-amber-600" if sev == "MEDIUM" else "text-slate-500"
            issues_html += f'<li class="text-sm {sev_cls}"><strong>[{sev}]</strong> {g.get("description","")}</li>'
    if open_qs:
        for q in open_qs:
            issues_html += f'<li class="text-sm text-blue-600">❓ {q.get("question","")}</li>'
    if conflicts:
        for c in conflicts:
            issues_html += f'<li class="text-sm text-red-700">⚡ CONFLICT: {c.get("description","")}</li>'

    issues_section = ""
    if issues_html:
        issues_section = f"""<div class="card mt-4">
          <h3 class="text-sm font-semibold text-slate-700 mb-2">⚠ Gaps, Questions &amp; Conflicts</h3>
          <ul class="space-y-1">{issues_html}</ul>
        </div>"""

    # Requirement sections
    def section(label, content):
        if not content:
            return ""
        if isinstance(content, list):
            if not content:
                return ""
            items = "".join(f"<li class='text-sm text-slate-700'>{i if isinstance(i,str) else json.dumps(i)}</li>" for i in content)
            return f'<div class="mb-3"><div class="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-1">{label}</div><ul class="list-disc list-inside space-y-0.5">{items}</ul></div>'
        return f'<div class="mb-3"><div class="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-1">{label}</div><p class="text-sm text-slate-700">{content}</p></div>'

    def flow_section(label, steps):
        if not steps:
            return ""
        rows = ""
        for s in steps:
            if isinstance(s, dict):
                rows += f"""<tr class="border-b border-slate-100 last:border-0">
                  <td class="py-1.5 pr-3 text-xs text-slate-400 font-mono">{s.get('step','')}</td>
                  <td class="py-1.5 pr-3 text-xs text-indigo-700 font-medium">{s.get('actor','')}</td>
                  <td class="py-1.5 pr-3 text-sm text-slate-700">{s.get('action','')}</td>
                  <td class="py-1.5 text-sm text-slate-500 italic">{s.get('system_response','')}</td>
                </tr>"""
        return f"""<div class="mb-3">
          <div class="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-1">{label}</div>
          <table class="w-full text-left"><tbody>{rows}</tbody></table>
        </div>"""

    def ac_section(criteria):
        if not criteria:
            return ""
        rows = ""
        for ac in criteria:
            if isinstance(ac, dict):
                testable = ac.get("testable", True)
                flag = "" if testable else ' <span class="text-red-500 text-xs font-semibold">[NOT TESTABLE]</span>'
                rows += f"""<div class="flex items-start gap-2 py-1.5 border-b border-slate-100 last:border-0">
                  <span class="text-xs font-mono text-indigo-600 flex-shrink-0 pt-0.5">{ac.get('id','')}</span>
                  <p class="text-sm text-slate-700">{ac.get('text','')}{flag}</p>
                </div>"""
        return f'<div class="mb-3"><div class="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-1">Acceptance Criteria</div>{rows}</div>'

    status = req.get("_status", "DRAFT")
    status_cls = {"DRAFT":"bg-slate-100 text-slate-600","UNDER_REVIEW":"bg-amber-100 text-amber-700","APPROVED":"bg-emerald-100 text-emerald-700","REJECTED":"bg-red-100 text-red-700"}.get(status,"bg-slate-100 text-slate-600")

    reject_note = ""
    if status == "REJECTED" and req.get("_reject_reason"):
        reject_note = f'<div class="bg-red-50 border border-red-200 text-red-700 text-sm px-4 py-3 rounded-lg mb-4">Rejected: {req["_reject_reason"]}</div>'

    action_btn = ""
    if status == "DRAFT":
        action_btn = """<form method="POST" action="/submit-for-approval" class="mt-4">
          <button type="submit" class="w-full py-2.5 bg-indigo-600 hover:bg-indigo-700 text-white font-medium rounded-lg text-sm transition-colors">
            Submit for Approval →
          </button>
        </form>"""
    elif status == "REJECTED":
        action_btn = '<div class="mt-4 text-sm text-slate-500 text-center">Requirement rejected. Upload revised sources and re-extract.</div>'
    elif status == "APPROVED":
        action_btn = '<div class="mt-4 text-sm text-emerald-600 font-medium text-center">✓ Approved — proceed to test generation</div>'

    return f"""
    {reject_note}

    <div class="grid grid-cols-1 lg:grid-cols-3 gap-4">

      <!-- Left: candidates -->
      <div>
        <div class="card">
          <h2 class="text-sm font-semibold text-slate-700 mb-3">Extracted Candidates ({len(candidates)})</h2>
          <div class="max-h-80 overflow-y-auto">{cand_html}</div>
        </div>
        {issues_section}
      </div>

      <!-- Right: composed requirement -->
      <div class="lg:col-span-2">
        <div class="card">
          <div class="flex items-start justify-between mb-4">
            <div>
              <div class="text-xs text-slate-400 font-mono mb-0.5">{req.get('req_id','')}</div>
              <h2 class="text-lg font-bold text-slate-800">{req.get('title','Untitled Requirement')}</h2>
            </div>
            <div class="flex items-center gap-2 flex-shrink-0">
              <span class="px-2.5 py-1 rounded-full text-xs font-semibold {status_cls}">{status}</span>
              <div class="text-right">
                <div class="text-xs text-slate-400">Quality</div>
                <div class="text-sm font-bold text-{qs_color}-600">{qs_pct}%</div>
              </div>
            </div>
          </div>

          <div class="max-h-[60vh] overflow-y-auto pr-1 space-y-1">
            {section("Business Objective", req.get("business_objective",""))}
            {section("Background", req.get("background",""))}
            {section("In Scope", req.get("in_scope",[]))}
            {section("Out of Scope", req.get("out_of_scope",[]))}
            {section("Trigger", req.get("trigger",""))}
            {section("Preconditions", req.get("preconditions",[]))}
            {flow_section("Main Flow", req.get("main_flow",[]))}
            {section("Business Rules", req.get("business_rules",[]))}
            {ac_section(req.get("acceptance_criteria",[]))}
            {section("Assumptions", [a.get("text","") + (" ⚑" if a.get("is_inferred") else "") for a in req.get("assumptions",[]) if isinstance(a,dict)])}
            {section("Open Questions", [q.get("question","") + (" [BLOCKING]" if q.get("blocking") else "") for q in req.get("open_questions",[]) if isinstance(q,dict)])}
            {section("Risks", [f'{r.get("severity","")}: {r.get("description","")}' for r in req.get("risks",[]) if isinstance(r,dict)])}
          </div>

          {action_btn}
        </div>
      </div>
    </div>"""


def page_approval(state: dict) -> str:
    req = state.get("requirement", {})
    return f"""
    <div class="max-w-2xl mx-auto">
      <div class="card mb-4">
        <div class="flex items-center justify-between mb-4">
          <div>
            <div class="text-xs font-mono text-slate-400">{req.get('req_id','')}</div>
            <h2 class="text-lg font-bold text-slate-800">{req.get('title','')}</h2>
          </div>
          <span class="px-2.5 py-1 bg-amber-100 text-amber-700 rounded-full text-xs font-semibold">UNDER REVIEW</span>
        </div>
        <p class="text-sm text-slate-600 mb-4">{req.get('business_objective','')}</p>

        <div class="mb-4">
          <div class="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-2">Acceptance Criteria</div>
          {"".join(f'<div class="flex items-start gap-2 py-1.5 border-b border-slate-100 last:border-0"><span class="text-xs font-mono text-indigo-600 flex-shrink-0">{ac.get("id","")}</span><p class="text-sm text-slate-700">{ac.get("text","")}</p></div>' for ac in req.get("acceptance_criteria",[]) if isinstance(ac,dict))}
        </div>

        <div class="mb-4">
          <div class="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-1">Business Rules</div>
          <ul class="list-disc list-inside space-y-0.5">
            {"".join(f'<li class="text-sm text-slate-700">{r}</li>' for r in req.get("business_rules",[]))}
          </ul>
        </div>

        <div class="text-xs text-slate-400">Quality score: {int(req.get('quality_score',0)*100)}% &nbsp;|&nbsp; {len(req.get('acceptance_criteria',[]))} acceptance criteria &nbsp;|&nbsp; {len(req.get('business_rules',[]))} business rules</div>
      </div>

      <!-- Approve -->
      <div class="grid grid-cols-1 sm:grid-cols-2 gap-3">
        <form method="POST" action="/approve">
          <div class="card border-emerald-200 bg-emerald-50 text-center">
            <div class="text-2xl mb-2">✓</div>
            <h3 class="font-semibold text-emerald-800 mb-1">Approve</h3>
            <p class="text-xs text-emerald-700 mb-3">Requirement is complete and testable. Proceed to test generation.</p>
            <button type="submit"
              class="w-full py-2 bg-emerald-600 hover:bg-emerald-700 text-white text-sm font-medium rounded-lg transition-colors">
              Approve Requirement
            </button>
          </div>
        </form>

        <!-- Reject -->
        <form method="POST" action="/reject">
          <div class="card border-red-200 bg-red-50 text-center">
            <div class="text-2xl mb-2">✕</div>
            <h3 class="font-semibold text-red-800 mb-1">Reject</h3>
            <p class="text-xs text-red-700 mb-2">Requirement needs revision before it can be used for testing.</p>
            <textarea name="reason" rows="2" placeholder="Reason for rejection..."
              class="w-full px-2 py-1.5 text-xs border border-red-200 rounded-lg mb-2 focus:outline-none bg-white"></textarea>
            <button type="submit"
              class="w-full py-2 bg-red-600 hover:bg-red-700 text-white text-sm font-medium rounded-lg transition-colors">
              Reject Requirement
            </button>
          </div>
        </form>
      </div>
    </div>"""


def page_tests(state: dict) -> str:
    req = state.get("requirement", {})
    test_cases = state.get("test_cases", [])

    if not test_cases:
        return f"""
        <div class="max-w-xl mx-auto text-center">
          <div class="card">
            <div class="w-14 h-14 bg-emerald-100 rounded-2xl flex items-center justify-center mx-auto mb-4">
              <svg class="w-7 h-7 text-emerald-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/>
              </svg>
            </div>
            <h2 class="text-lg font-bold text-slate-800 mb-1">Requirement Approved</h2>
            <p class="text-sm text-slate-500 mb-1 font-mono">{req.get('req_id','')}</p>
            <p class="text-sm text-slate-500 mb-4">{req.get('title','')}</p>
            <form method="POST" action="/generate-tests">
              <button type="submit" onclick="showSpinner(this,'Generating test cases...')"
                class="w-full py-2.5 bg-indigo-600 hover:bg-indigo-700 text-white font-medium rounded-lg text-sm transition-colors">
                ⚡ Generate Test Cases
              </button>
              <p class="text-xs text-slate-400 mt-2">Takes 30–60 seconds. Generates POSITIVE, NEGATIVE, BOUNDARY, EXCEPTION, SECURITY, and WORKFLOW tests.</p>
            </form>
          </div>
        </div>"""

    # Group by scenario_group
    groups = {}
    for tc in test_cases:
        grp = tc.get("scenario_group", "General")
        groups.setdefault(grp, []).append(tc)

    type_colors = {
        "POSITIVE":"badge-positive","NEGATIVE":"badge-negative","BOUNDARY":"badge-boundary",
        "SECURITY":"badge-security","WORKFLOW":"badge-workflow","EXCEPTION":"badge-exception-test",
        "INTEGRATION":"badge-integration","DATA_VALIDATION":"badge-data",
    }
    prio_colors = {"CRITICAL":"text-red-600","HIGH":"text-amber-600","MEDIUM":"text-slate-600","LOW":"text-slate-400"}

    groups_html = ""
    for grp_name, cases in groups.items():
        cases_html = ""
        for tc in cases:
            tt = tc.get("test_type","").upper()
            badge = type_colors.get(tt, "badge-other")
            prio = tc.get("priority","MEDIUM")
            prio_cls = prio_colors.get(prio, "text-slate-500")

            steps_html = ""
            for s in tc.get("steps", []):
                if isinstance(s, dict):
                    steps_html += f"""<tr class="border-b border-slate-100 last:border-0">
                      <td class="py-1 pr-3 text-xs text-slate-400 font-mono w-6">{s.get('step','')}</td>
                      <td class="py-1 pr-4 text-xs text-slate-700">{s.get('action','')}</td>
                      <td class="py-1 text-xs text-emerald-700">{s.get('expected_result','')}</td>
                    </tr>"""

            notes = f'<p class="text-xs text-amber-700 mt-2 bg-amber-50 rounded px-2 py-1">📋 {tc.get("sap_commissions_notes","")}</p>' if tc.get("sap_commissions_notes") else ""

            cases_html += f"""
            <div class="border border-slate-200 rounded-lg p-3 mb-3">
              <div class="flex items-start justify-between gap-2 mb-2">
                <div>
                  <div class="flex items-center gap-2">
                    <span class="text-xs font-mono text-slate-400">{tc.get('case_id','')}</span>
                    <span class="px-1.5 py-0.5 rounded text-xs font-semibold {badge}">{tt}</span>
                    <span class="text-xs {prio_cls} font-semibold">{prio}</span>
                  </div>
                  <h4 class="text-sm font-semibold text-slate-800 mt-0.5">{tc.get('title','')}</h4>
                </div>
                <span class="text-xs text-indigo-600 font-mono flex-shrink-0">{tc.get('acceptance_criterion_id','')}</span>
              </div>
              <p class="text-xs text-slate-500 mb-2">{tc.get('objective','')}</p>
              <table class="w-full text-left mb-1"><tbody>{steps_html}</tbody></table>
              <div class="text-xs font-semibold text-emerald-700 mt-1">✓ {tc.get('overall_expected_result','')}</div>
              {notes}
            </div>"""

        groups_html += f"""
        <div class="card mb-4">
          <h3 class="text-sm font-semibold text-slate-700 mb-3 pb-2 border-b border-slate-100">{grp_name}</h3>
          {cases_html}
        </div>"""

    summary_counts = {}
    for tc in test_cases:
        t = tc.get("test_type","OTHER")
        summary_counts[t] = summary_counts.get(t, 0) + 1

    summary_html = "".join(
        f'<span class="px-2 py-1 bg-slate-100 text-slate-600 rounded text-xs font-medium">{k}: {v}</span>'
        for k, v in summary_counts.items()
    )

    return f"""
    <div class="flex items-center justify-between mb-4">
      <div>
        <h2 class="text-lg font-bold text-slate-800">{req.get('title','')} — Test Cases</h2>
        <div class="flex flex-wrap gap-1.5 mt-1">{summary_html}</div>
      </div>
      <a href="/export" class="px-4 py-2 bg-slate-800 hover:bg-slate-900 text-white text-sm font-medium rounded-lg transition-colors">
        ↓ Export JSON
      </a>
    </div>
    {groups_html}"""


# ── Routes ─────────────────────────────────────────────────────────────────────

@app.route("/")
def index():
    sid = session.setdefault("sid", str(uuid.uuid4()))
    state = get_state(sid)
    state["stage"] = "intake"
    return render_template_string(base(page_intake(state), "intake", state.get("error")))


@app.route("/upload-file", methods=["POST"])
def upload_file():
    sid = session.setdefault("sid", str(uuid.uuid4()))
    state = get_state(sid)
    state["error"] = None

    f = request.files.get("file")
    component = request.form.get("component", "Workflow")
    state["component"] = component

    if not f or not f.filename:
        state["error"] = "No file selected."
        return redirect(url_for("index"))

    content = parse_upload(f)
    state["sources"].append({
        "id": str(uuid.uuid4()),
        "name": f.filename,
        "type": f.filename.rsplit(".", 1)[-1].upper() if "." in f.filename else "FILE",
        "content": content,
        "uploaded_at": datetime.now().strftime("%Y-%m-%d %H:%M"),
    })
    return redirect(url_for("index"))


@app.route("/upload-text", methods=["POST"])
def upload_text():
    sid = session.setdefault("sid", str(uuid.uuid4()))
    state = get_state(sid)
    state["error"] = None

    content = request.form.get("content", "").strip()
    name = request.form.get("name", "Pasted text").strip() or "Pasted text"
    component = request.form.get("component", "Workflow")
    state["component"] = component

    if not content:
        state["error"] = "No content provided."
        return redirect(url_for("index"))

    state["sources"].append({
        "id": str(uuid.uuid4()),
        "name": name,
        "type": "PASTED",
        "content": content,
        "uploaded_at": datetime.now().strftime("%Y-%m-%d %H:%M"),
    })
    return redirect(url_for("index"))


@app.route("/extract", methods=["POST"])
def extract():
    sid = session.setdefault("sid", str(uuid.uuid4()))
    state = get_state(sid)
    state["error"] = None

    if not state["sources"]:
        state["error"] = "Upload at least one source before extracting."
        return redirect(url_for("index"))

    # Combine all source text
    combined = "\n\n===== SOURCE SEPARATOR =====\n\n".join(
        f"[{s['name']}]\n{s['content']}" for s in state["sources"]
    )
    component = state["component"]

    try:
        extraction = ai_extract(combined, component)
        state["candidates"]     = extraction.get("candidates", [])
        state["gaps"]           = extraction.get("gaps", [])
        state["open_questions"] = extraction.get("open_questions", [])
        state["conflicts"]      = extraction.get("conflicts", [])

        req = ai_compose(
            state["candidates"],
            state["gaps"],
            state["open_questions"],
            component,
        )
        req["_status"] = "DRAFT"
        state["requirement"] = req
        state["stage"] = "review"
    except Exception as e:
        state["error"] = f"AI extraction failed: {e}"
        return redirect(url_for("index"))

    return redirect(url_for("review"))


@app.route("/review")
def review():
    sid = session.setdefault("sid", str(uuid.uuid4()))
    state = get_state(sid)
    if not state.get("requirement"):
        return redirect(url_for("index"))
    stage = state.get("stage", "review")
    return render_template_string(base(page_review(state), stage, state.get("error")))


@app.route("/submit-for-approval", methods=["POST"])
def submit_for_approval():
    sid = session.setdefault("sid", str(uuid.uuid4()))
    state = get_state(sid)
    if state.get("requirement"):
        state["requirement"]["_status"] = "UNDER_REVIEW"
        state["stage"] = "approval"
    return redirect(url_for("approval"))


@app.route("/approval")
def approval():
    sid = session.setdefault("sid", str(uuid.uuid4()))
    state = get_state(sid)
    if not state.get("requirement"):
        return redirect(url_for("index"))
    return render_template_string(base(page_approval(state), "approval"))


@app.route("/approve", methods=["POST"])
def approve():
    sid = session.setdefault("sid", str(uuid.uuid4()))
    state = get_state(sid)
    if state.get("requirement"):
        state["requirement"]["_status"] = "APPROVED"
        state["requirement"]["_approved_at"] = datetime.now().isoformat()
        state["stage"] = "tests"
    return redirect(url_for("tests"))


@app.route("/reject", methods=["POST"])
def reject():
    sid = session.setdefault("sid", str(uuid.uuid4()))
    state = get_state(sid)
    reason = request.form.get("reason", "No reason given.")
    if state.get("requirement"):
        state["requirement"]["_status"] = "REJECTED"
        state["requirement"]["_reject_reason"] = reason
        state["stage"] = "review"
    return redirect(url_for("review"))


@app.route("/tests")
def tests():
    sid = session.setdefault("sid", str(uuid.uuid4()))
    state = get_state(sid)
    if not state.get("requirement") or state["requirement"].get("_status") != "APPROVED":
        return redirect(url_for("index"))
    return render_template_string(base(page_tests(state), "tests"))


@app.route("/generate-tests", methods=["POST"])
def generate_tests():
    sid = session.setdefault("sid", str(uuid.uuid4()))
    state = get_state(sid)

    # Hard gate — enforced in route, not just UI
    req = state.get("requirement")
    if not req or req.get("_status") != "APPROVED":
        state["error"] = "Test generation is blocked. Requirement must be approved first."
        return redirect(url_for("index"))

    try:
        state["test_cases"] = ai_generate_tests(req, state["component"])
        state["stage"] = "tests"
    except Exception as e:
        state["error"] = f"Test generation failed: {e}"
        return redirect(url_for("tests"))

    return redirect(url_for("tests"))


@app.route("/export")
def export():
    sid = session.setdefault("sid", str(uuid.uuid4()))
    state = get_state(sid)
    req = state.get("requirement", {})
    output = {
        "export_timestamp": datetime.now().isoformat(),
        "requirement_id": req.get("req_id", ""),
        "requirement_title": req.get("title", ""),
        "component": state.get("component", ""),
        "approved_at": req.get("_approved_at", ""),
        "test_cases": state.get("test_cases", []),
    }
    return Response(
        json.dumps(output, indent=2),
        mimetype="application/json",
        headers={"Content-Disposition": f'attachment; filename="commspec_{req.get("req_id","tests")}.json"'},
    )


if __name__ == "__main__":
    app.run(debug=True, port=5002)
